matrix:
- name: fr
  group: Markdown
  expect_match: false
  aspell:
    lang: fr
    d: fr_FR
  dictionary:
    wordlists:
    - .github/.wordlist.fr-FR.txt
    output: wordlist.fr-FR.dic
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.extra:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - alt
      ignores:
      - ':matches(code, pre)'
      - 'code'
      - 'pre'
      - 'blockquote'
  sources:
  - 'README.fr-FR.md'
