matrix:
- name: es
  group: Markdown
  expect_match: false
  aspell:
    lang: es
    d: es_ES
  dictionary:
    wordlists:
    - .github/.wordlist.es-ES.txt
    output: wordlist.es-ES.dic
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.extra:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - alt
      ignores:
      - ':matches(code, pre)'
      - 'code'
      - 'pre'
      - 'blockquote'
  sources:
  - 'README.es-ES.md'
