matrix:
- name: English
  aspell:
    lang: en
  dictionary:
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources: "README.md CONTRIBUTING.md"
  default_encoding: utf-8
- name: French
  aspell:
    lang: fr
  dictionary:
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources: "README.fr-FR.md"
  default_encoding: utf-8
- name: Spanish
  aspell:
    lang: es
  dictionary:
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources: "README.es-ES.md"
  default_encoding: utf-8
