name: Markdownlint Action
on:
  # Enabling manual test
  # REF: https://stackoverflow.com/questions/58933155/manual-workflow-triggers-in-github-actions
  workflow_dispatch:
  push:

jobs:
  build:
    name: Markdownlint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nosborn/github-action-markdown-cli@v3.2.0
      name: Markdownlint
      with:
        files: .
        config_file: ".github/.markdownlint.json"
